import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import Feed from '../components/feed'
import Widgets from '../components/widgets'

const Home: NextPage = () => {
  return (
    <div className="lg:max-w-6xl mx-auto max-h-screen overflow-hidden">
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-9 ">
        <div className="col-span-2">
          <Sidebar />
        </div>

        <div className="col-span-7 lg:col-span-5">
          <Feed />
        </div>


        <div className="col-span-2 hidden lg:inline">
         <Widgets />
        </div>
      </main>
      
    </div>
  )
}

export default Home
